import = ["~/.alacrittythemes/everforest.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
#startup_mode = "Fullscreen"
#decorations = "None"
opacity = 0.9
padding = {x=10, y=10}

[font]
size=14.0

[font.bold]
family = "GohuFont 14 Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GohuFont 14 Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "GohuFont 14 Nerd Font"
style = "Italic"

[font.normal]
family = "GohuFont 14 Nerd Font"
style = "Regular"
