import = ["/home/load/.alacrittythemes/gruvbox.toml", "/home/load/.alacrittythemes/font.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10
