import = ["~/.alacrittythemes/catppuccin.toml", "~/.alacrittythemes/font.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10
