[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
#startup_mode = "Fullscreen"
#decorations = "None"
opacity = 1
padding = {x=20, y=20}

[general]
live_config_reload = true
import = ["~/.alacrittythemes/catppuccin.toml"]

[font]
size = 12.0

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
