[colors.primary]
background = '#1c1c1c'
foreground = '#c0c0c0'

[colors.normal]
black =   '#303030'
red =     '#1bfd9c'
green =   '#bdfe58'
yellow =  '#1bfd9c'
blue =    '#e6e6e6'
magenta = '#c5c5c5'
cyan =    '#b2d8d8'
white =   '#d4be98'


#fg = "#c0c0c0",
#bg = "#1c1c1c",
#cursor = "#bdfe58",
#line_nr = "#404040",
#visual = "#303030",
#comment = "#585858",
#string = "#d1d1d1",
#func = "#e1e1e1",
#kw = "#f1f1f1",
#identifier = "#b1b1b1",
#type = "#a1a1a1",
#type_builtin = "#c5c5c5",
#search_highlight = "#1bfd9c",
#operator = "#1bfd9c",
#bracket = "#e6e6e6",
#preprocessor = "#4b8902",
#bool = "#66b2b2",
#constant = "#b2d8d8",
#glow_color = "#1bfd9c",
