[colors.primary]
background = '#080808'  # Pure black for contrast
foreground = '#F8F8FF'  # White for higher contrast

[colors.normal]
black   = '#080808'  # Pure black for deep contrast
red     = '#ed1b76'  # Bright pink (keyword, warning)
green   = '#f44786'  # White to match the aesthetic
yellow  = '#F8F8F8'  # Softer pink for accents (builtin, warning2)
blue    = '#f15599'  # White for text contrast
magenta = '#f15599'  # Stronger neon pink (keyword, warning)
cyan    = '#FCD9E8'  # Pure white for strong contrast
white   = '#F8F8FF'  # Pure white for strong contrast

[colors.cursor]
text   = '#080808'  # Black text for cursor
cursor = '#ed1b76'  # Matching bright pink for cursor
